# Site settings
title: 生命不止，折腾不息
author: Nanxuan Li
author_avatar: /images/header.jpg
email: lanceli31@163.com
description: 生命不止，折腾不息 
url: "https://crazylnx.github.io/"
domain: "https://crazylnx.github.io/"
github_username: nanxuanl
github_site_repo: https://crazylnx.github.io/
disqus: Nanxuan Li


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    syntax_highlighter: rouge
    extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]

sass:
    style: :compressed
    sass_dir: _sass

permalink: pretty
excerpt_separator: "<!-- more -->"

# path
categories_path: categories/
tags_path: tags/


gems:
  - jekyll-sitemap
